# Generated by Django 6.0.3 on 2026-04-08 22:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=200)),
                ('date', models.DateTimeField()),
                ('capacity', models.IntegerField()),
                ('ticket_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='posters/')),
                ('category', models.CharField(choices=[('hackathon', 'Hackathons'), ('tech-summit', 'Tech Summits'), ('workshop', 'Workshops'), ('networking', 'Networking'), ('campus', 'Campus Life'), ('club', 'Clubs')], default='campus', max_length=50)),
            ],
        ),
    ]
