# Generated by Django 6.0.3 on 2026-04-08 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('hackathon', 'Hackathons'), ('tech-summit', 'Tech Summits'), ('workshop', 'Workshops'), ('networking', 'Networking'), ('campus', 'Campus Life'), ('club', 'Clubs')], default='campus', max_length=50),
        ),
    ]
