# Generated by Django 6.0.3 on 2026-03-10 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='purchase_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
